# Generated by Django 4.2.2 on 2023-07-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=8)),
            ],
        ),
    ]
