# Generated by Django 4.2.2 on 2023-07-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0002_likeresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeResponse',
        ),
    ]
