# Generated by Django 4.2.2 on 2023-07-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0003_delete_likeresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likestat',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_social_app.user'),
        ),
    ]
